#ifndef EI_TFLITE_MODEL_OPS_DEFINES_H
#define EI_TFLITE_MODEL_OPS_DEFINES_H

#include <stdint.h>

// Ce fichier liste les opérations mathématiques nécessaires pour vos deux modèles
#define EI_TFLITE_MODEL_CUSTOM_OPS_ONLY
#define EI_TFLITE_MODEL_LOAD_ADD 1
#define EI_TFLITE_MODEL_LOAD_CONV_2D 1
#define EI_TFLITE_MODEL_LOAD_DEPTHWISE_CONV_2D 1
#define EI_TFLITE_MODEL_LOAD_FULLY_CONNECTED 1
#define EI_TFLITE_MODEL_LOAD_MAX_POOL_2D 1
#define EI_TFLITE_MODEL_LOAD_RESHAPE 1
#define EI_TFLITE_MODEL_LOAD_SOFTMAX 1
#define EI_TFLITE_MODEL_LOAD_AVERAGE_POOL_2D 1
#define EI_TFLITE_MODEL_LOAD_MUL 1
#define EI_TFLITE_MODEL_LOAD_QUANTIZE 1
#define EI_TFLITE_MODEL_LOAD_DEQUANTIZE 1

#endif // EI_TFLITE_MODEL_OPS_DEFINES_H
